// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _cal from "./cal";
export type $GameResult = {
  "1-0": $.$expr_Literal<$GameResult>;
  "0-1": $.$expr_Literal<$GameResult>;
  "1/2-1/2": $.$expr_Literal<$GameResult>;
  "*": $.$expr_Literal<$GameResult>;
} & $.EnumType<"default::GameResult", ["1-0", "0-1", "1/2-1/2", "*"]>;
const GameResult: $GameResult = $.makeType<$GameResult>(_.spec, "68b9dfbe-5aea-11ef-a2bb-d7c28223b2fe", _.syntax.literal);

export type $GameSourceKind = {
  "Lichess": $.$expr_Literal<$GameSourceKind>;
} & $.EnumType<"default::GameSourceKind", ["Lichess"]>;
const GameSourceKind: $GameSourceKind = $.makeType<$GameSourceKind>(_.spec, "0a4c02bf-5bf0-11ef-b4a8-c38217a9d370", _.syntax.literal);

export type $ChessDatabaseλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "games": $.LinkDesc<$Game, $.Cardinality.Many, {}, false, true,  false, false>;
  "sources": $.LinkDesc<$GameSource, $.Cardinality.Many, {}, false, true,  false, false>;
  "<chessDatabase[is Game]": $.LinkDesc<$Game, $.Cardinality.Many, {}, false, false,  false, false>;
  "<chessDatabase[is GameSource]": $.LinkDesc<$GameSource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<chessDatabase[is LichessSource]": $.LinkDesc<$LichessSource, $.Cardinality.Many, {}, false, false,  false, false>;
  "<chessDatabase": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $ChessDatabase = $.ObjectType<"default::ChessDatabase", $ChessDatabaseλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $ChessDatabase = $.makeType<$ChessDatabase>(_.spec, "aab2ab26-452d-11ef-bb66-dfe3a0f6b655", _.syntax.literal);

const ChessDatabase: $.$expr_PathNode<$.TypeSet<$ChessDatabase, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ChessDatabase, $.Cardinality.Many), null);

export type $GameλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "pgn": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "white": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "black": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "blackElo": $.PropertyDesc<_std.$int32, $.Cardinality.AtMostOne, false, false, false, false>;
  "date": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "result": $.PropertyDesc<$GameResult, $.Cardinality.One, false, false, false, false>;
  "whiteElo": $.PropertyDesc<_std.$int32, $.Cardinality.AtMostOne, false, false, false, false>;
  "event": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "chessDatabase": $.LinkDesc<$ChessDatabase, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "gameSource": $.LinkDesc<$GameSource, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "<games[is ChessDatabase]": $.LinkDesc<$ChessDatabase, $.Cardinality.Many, {}, false, false,  false, false>;
  "<games": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Game = $.ObjectType<"default::Game", $GameλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Game = $.makeType<$Game>(_.spec, "81e35c8f-453c-11ef-8d46-2f96a408312c", _.syntax.literal);

const Game: $.$expr_PathNode<$.TypeSet<$Game, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Game, $.Cardinality.Many), null);

export type $GameSourceλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "chessDatabase": $.LinkDesc<$ChessDatabase, $.Cardinality.One, {}, false, false,  false, false>;
  "kind": $.PropertyDesc<$GameSourceKind, $.Cardinality.One, false, false, false, false>;
  "lastGameTimestamp": $.PropertyDesc<_std.$int64, $.Cardinality.AtMostOne, false, false, false, false>;
  "lastImportDate": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "username": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<sources[is ChessDatabase]": $.LinkDesc<$ChessDatabase, $.Cardinality.Many, {}, false, false,  false, false>;
  "<gameSource[is Game]": $.LinkDesc<$Game, $.Cardinality.Many, {}, false, false,  false, false>;
  "<gameSource": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sources": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $GameSource = $.ObjectType<"default::GameSource", $GameSourceλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $GameSource = $.makeType<$GameSource>(_.spec, "0a4c109b-5bf0-11ef-8e10-b1580560bb9b", _.syntax.literal);

const GameSource: $.$expr_PathNode<$.TypeSet<$GameSource, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($GameSource, $.Cardinality.Many), null);

export type $LichessSourceλShape = $.typeutil.flatten<$GameSourceλShape & {
  "importBlitz": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "importBullet": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "importClassical": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "importCorrespondence": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "importRapid": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "importUltraBullet": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
}>;
type $LichessSource = $.ObjectType<"default::LichessSource", $LichessSourceλShape, null, [
  ...$GameSource['__exclusives__'],
]>;
const $LichessSource = $.makeType<$LichessSource>(_.spec, "0a4f4864-5bf0-11ef-8ed4-f97dc3880930", _.syntax.literal);

const LichessSource: $.$expr_PathNode<$.TypeSet<$LichessSource, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($LichessSource, $.Cardinality.Many), null);

export type $MovieλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "actors": $.LinkDesc<$Person, $.Cardinality.Many, {}, false, false,  false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Movie = $.ObjectType<"default::Movie", $MovieλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Movie = $.makeType<$Movie>(_.spec, "6b60ccca-452c-11ef-a4f6-9139d3270585", _.syntax.literal);

const Movie: $.$expr_PathNode<$.TypeSet<$Movie, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Movie, $.Cardinality.Many), null);

export type $PersonλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<actors[is Movie]": $.LinkDesc<$Movie, $.Cardinality.Many, {}, false, false,  false, false>;
  "<actors": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Person = $.ObjectType<"default::Person", $PersonλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Person = $.makeType<$Person>(_.spec, "6b5f8fb6-452c-11ef-95dd-519acee85fed", _.syntax.literal);

const Person: $.$expr_PathNode<$.TypeSet<$Person, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Person, $.Cardinality.Many), null);



export { GameResult, GameSourceKind, $ChessDatabase, ChessDatabase, $Game, Game, $GameSource, GameSource, $LichessSource, LichessSource, $Movie, Movie, $Person, Person };

type __defaultExports = {
  "GameResult": typeof GameResult;
  "GameSourceKind": typeof GameSourceKind;
  "ChessDatabase": typeof ChessDatabase;
  "Game": typeof Game;
  "GameSource": typeof GameSource;
  "LichessSource": typeof LichessSource;
  "Movie": typeof Movie;
  "Person": typeof Person
};
const __defaultExports: __defaultExports = {
  "GameResult": GameResult,
  "GameSourceKind": GameSourceKind,
  "ChessDatabase": ChessDatabase,
  "Game": Game,
  "GameSource": GameSource,
  "LichessSource": LichessSource,
  "Movie": Movie,
  "Person": Person
};
export default __defaultExports;
