name: Test set-up node

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Setup Yarn
      run: npm install -g pnpm
    - name: Yarn Install 
      run: pnpm install
